base_model: google/gemma-4-31B-it
freeze_mm_modules: true
chat_template: gemma4
plugins:
- axolotl.integrations.liger.LigerPlugin
- axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin
cut_cross_entropy: true
liger_rope: true
liger_rms_norm: true
liger_layer_norm: true
liger_glu_activation: true
liger_rms_norm_gated: true
torch_compile: true
load_in_8bit: false
load_in_4bit: false
shuffle_merged_datasets: true
datasets:
- path: EVA-UNIT-01/Musica
  type: chat_template
  field_messages: conversations
  message_property_mappings:
    role: from
    content: value
dataset_prepared_path: ./last_run_prepared_custom
val_set_size: 0
output_dir: ./outputs/v1-custom-best
adapter: lora
save_safetensors: true
sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true
lora_r: 64
lora_alpha: 64
lora_dropout: 0.08043333888053894
lora_target_modules: model.language_model.layers.[\d]+.(_checkpoint_wrapped_module.)?(mlp|self_attn).(up|down|gate|q|k|v|o)_proj
lora_mlp_kernel: false
lora_qkv_kernel: false
lora_o_kernel: false
gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_torch_fused
lr_scheduler: constant
learning_rate: 1.3695818695008213e-06
warmup_ratio: 0.06330609261989593
max_grad_norm: 0.9016158759593964
bf16: auto
use_comet: true
comet_project_name: musica-31b
auto_resume_from_checkpoints: false
logging_steps: 1
sdp_attention: true
evals_per_epoch: 0
saves_per_epoch: 4
save_total_limit: 4
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: false
deepspeed: deepspeed_configs/zero3_bf16.json
